export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ALL_USERSLIST_SUCCESS = "ALL_USERSLIST_SUCCESS "
export const ALL_USERSLIST_FAIL= "ALL_USERSLIST_FAIL"

export const NOTE_CREATED_SUCCESS = "NOTE_CREATED_SUCCESS";
export const NOTE_CREATED_FAIL = "NOTE_CREATED_FAIL ";

export const NOTE_LIST_SUCCESS="NOTE_LIST_SUCCESS"
export const NOTE_LIST_FAIL="NOTE_LIST_FAIL"

export const REMOVE_NOTE_SUCCESS = "REMOVE_NOTE_SUCCESS"
export const REMOVE_NOTE_FAIL ="REMOVE_NOTE_FAIL"

export const SINGLE_NOTE_SUCCESS = "SINGLE_NOTE_SUCCESS"
export const SINGLE_NOTE_FAIL = "SINGLE_NOTE_FAIL"

export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL "